spring:
  config:
    import: optional:configserver:http://127.0.0.1:8888/
  profiles:
    active: native
  application:
  name: eureka-service
server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false


